seed: 0
mixed_precision: false
base_lr: 4.0e-4

nr_gpus: 1
batch_size: 4
n_total_epoch: 600
minibatch_per_epoch: 500

loadmodel: ~
log_dir: "./train_log"
model_save_freq_epoch: 1

max_disp: 256
image_width: 960
image_height: 540
training_data_path: "F:\\Datasets\\spring\\spring"

log_level: "logging.INFO"
dist: True # True for DDP, False for DP
